version: "3.8"

services:
  back:
    image: mediatech-back
    ports:
      - 3001:3001
    secrets:
      - freebox_secret
      - omdbapi_secret
      - certificate
      - private_key
      - jwt_secret
    environment:
      USE_HTTPS: "true"
      FREEBOX_USE_FTPS: "false"
      FREEBOX_USER: "freebox"
      FREEBOX_HOST: "mafreebox.freebox.fr"
      FREEBOX_PORT: "21"
      FREEBOX_MEDIA_FOLDER: "Freebox/Media/Films"
      NODE_ENV: "prod"
      MONGODB_URI: "mongodb://localhost:27017/mediatech"
    deploy:
      replicas: 1  # Set the number of replicas to deploy
      restart_policy:
        condition: on-failure  # Define a restart policy
    networks:
      - mediatech-network

  front:
    image: mediatech-front
    ports:
      - 3000:3000
    depends_on:
      - back
    environment:
      REACT_APP_BACK_URL: "192.168.1.149"
      HTTPS: "true"
      REACT_APP_HTTPS: "true"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - mediatech-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local

secrets:
  freebox_secret:
    external: true
  omdbapi_secret:
    external: true
  certificate:
    external: true
  private_key:
    external: true
  jwt_secret:
    external: true

networks:
  mediatech-network:
    driver: overlay