services:
  back:
    build:
      context: back/.
    ports:
      - 3001:3001
    secrets:
      - freebox_secret
      - omdbapi_secret
    environment:
      - FREEBOX_USE_FTPS=false
      - FREEBOX_HOST=mafreebox.freebox.fr
      - FREEBOX_USER=freebox
      - FREEBOX_PORT=21
      - FREEBOX_MEDIA_FOLDER=Freebox/Media/Films
  front:
    build:
      context: front/.
    ports:
      - 3000:3000
    depends_on:
      - back
    environment:
      - REACT_APP_BACK_URL=mediatech_back

secrets:
  freebox_secret:
    external: true
  omdbapi_secret:
    external: true