version: "3.8"

services:
  back:
    image: mediatech-back
    ports:
      - 3001:3001
    secrets:
      - freebox_secret
      - omdbapi_secret
    environment:
      FREEBOX_USE_FTPS: "false"
      FREEBOX_USER: "freebox"
      FREEBOX_PORT: "22"
      FREEBOX_MEDIA_FOLDER: "Freebox/Media/Films"
    deploy:
      replicas: 1  # Set the number of replicas to deploy
      restart_policy:
        condition: on-failure  # Define a restart policy

  front:
    image: mediatech-front
    ports:
      - 3000:3000
    depends_on:
      - back
    environment:
      REACT_APP_BACK_URL: "back"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  freebox_secret:
    external: true  # The secret is created externally and must be available to the swarm
  omdbapi_secret:
    external: true  # External secret available in Docker Swarm